name: Build and Publish Plugin

on:
  create:
    tags:
      - "*"
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  build-plugin-release:
    uses: BetterCorp/service-base-build-workflows/.github/workflows/node.yml@master
    with:
      PUBLISH: true
    secrets:
      NPM_TOKEN_PUB: ${{ secrets.NPM2_TOKEN_PUB }}
      NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
      NPM_NAME: ${{ secrets.NPM_NAME }}
